# Set the Docker image used for building the application.
image: appdoc_api:latest

# Define the pipeline steps.
pipelines:
  branches:
    devs:
      - step:
          name: Appdoc
          services:
            - docker
          caches:
            - docker
          script:
            # Log in to Docker Hub or other container registry.
            - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            # Export Docker
            - export IMAGE_NAME=my-docker-hub-repo/lumen_web:latest
            # Build the Docker image.
            - docker-compose build

            # Push the Docker image to Docker Hub or other container registry.
            - docker-compose push
            - ssh root@207.148.126.140 "cd /var/www/appdoc_api && docker-compose down && docker-compose pull && docker-compose up -d"
          # Define environment variables.
          environment:
            - DOCKER_USERNAME=xnuxuz
            - DOCKER_PASSWORD=Docker24'=''r'
