version: '1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: appdoc_api:latest
    container_name: appdoc_api
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - .:/var/www/appdoc_api
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:5.7
    container_name: database_appdoc
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dev_appdoc
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge